"""add_report_card_feedback_to_user_profile

Revision ID: 3e637942d43b
Revises: 6300cabbc52b
Create Date: 2026-03-06 17:23:21.914410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e637942d43b'
down_revision = '6300cabbc52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_card_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('report_card_feedback')

    # ### end Alembic commands ###
