"""Add Deck model, SRS fields, streak tracking

Revision ID: 55a8f913d279
Revises: 3e637942d43b
Create Date: 2026-03-13 01:41:37.690481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '55a8f913d279'
down_revision = '3e637942d43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('laoshi_message', sa.String(length=500), nullable=True),
    sa.Column('created_ds', sa.DateTime(), nullable=True),
    sa.Column('updated_ds', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_practice_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'deck', ['deck_id'], ['id'])

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ease_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('next_review_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_quality', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marked_as_known', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mastered', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'deck', ['deck_id'], ['id'])
        batch_op.drop_column('confidence_score')

    # ### Data migration: Create "My Words" deck for existing users and assign words ###
    connection = op.get_bind()

    # Get all users who have words
    users_with_words = connection.execute(text("""
        SELECT DISTINCT user_id FROM word
    """)).fetchall()

    for (user_id,) in users_with_words:
        # Check if user already has decks (idempotent)
        existing_decks = connection.execute(text("""
            SELECT COUNT(*) FROM deck WHERE user_id = :user_id
        """), {'user_id': user_id}).scalar()

        if existing_decks == 0:
            # Create "My Words" deck
            result = connection.execute(text("""
                INSERT INTO deck (name, description, user_id, created_ds, updated_ds)
                VALUES ('My Words', 'Imported vocabulary', :user_id, NOW(), NOW())
                RETURNING id
            """), {'user_id': user_id})
            deck_id = result.scalar()

            # Assign all user's words to this deck
            connection.execute(text("""
                UPDATE word SET deck_id = :deck_id WHERE user_id = :user_id
            """), {'deck_id': deck_id, 'user_id': user_id})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_mastered')
        batch_op.drop_column('marked_as_known')
        batch_op.drop_column('last_quality')
        batch_op.drop_column('next_review_date')
        batch_op.drop_column('ease_factor')
        batch_op.drop_column('interval_days')
        batch_op.drop_column('repetitions')
        batch_op.drop_column('deck_id')

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deck_id')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('last_practice_date')
        batch_op.drop_column('current_streak')

    op.drop_table('deck')
    # ### end Alembic commands ###
