"""add_user_profile_table

Revision ID: 6300cabbc52b
Revises: ee4a2028e5da
Create Date: 2026-02-27 17:37:09.229084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6300cabbc52b'
down_revision = 'ee4a2028e5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create user_profile table
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_name', sa.String(length=80), nullable=True),
    sa.Column('words_per_session', sa.Integer(), nullable=True),
    sa.Column('encrypted_deepseek_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_gemini_api_key', sa.Text(), nullable=True),
    sa.Column('deepseek_key_version', sa.Integer(), nullable=True),
    sa.Column('gemini_key_version', sa.Integer(), nullable=True),
    sa.Column('created_ds', sa.DateTime(), nullable=True),
    sa.Column('updated_ds', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    # Step 2: Data migration - copy preferred_name from user to user_profile
    op.execute("""
        INSERT INTO user_profile (user_id, preferred_name, deepseek_key_version, gemini_key_version, created_ds, updated_ds)
        SELECT id, preferred_name, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM "user"
        WHERE preferred_name IS NOT NULL
    """)

    # Step 3: Drop preferred_name from user table
    op.drop_column('user', 'preferred_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add preferred_name back to user table
    op.add_column('user', sa.Column('preferred_name', sa.String(length=80), nullable=True))

    # Step 2: Copy preferred_name back from user_profile to user
    op.execute("""
        UPDATE "user"
        SET preferred_name = user_profile.preferred_name
        FROM user_profile
        WHERE "user".id = user_profile.user_id
    """)

    # Step 3: Drop user_profile table
    op.drop_table('user_profile')
    # ### end Alembic commands ###
