"""add_onboarding_complete_to_user_profile

Revision ID: 67affe5c8824
Revises: 7d9e8b83cb7e
Create Date: 2026-04-08 11:43:57.325533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '67affe5c8824'
down_revision = '7d9e8b83cb7e'
branch_labels = None
depends_on = None


def upgrade():
    # Add column with server_default so existing rows get a value
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # Mark all existing profiles as onboarded (they're existing users)
    connection = op.get_bind()
    connection.execute(text("UPDATE user_profile SET onboarding_complete = true"))

    # Create profiles for users who don't have one yet, marked as onboarded
    connection.execute(text("""
        INSERT INTO user_profile (user_id, onboarding_complete, deepseek_key_version, gemini_key_version, current_streak)
        SELECT u.id, true, 1, 1, 0
        FROM "user" u
        LEFT JOIN user_profile up ON up.user_id = u.id
        WHERE up.id IS NULL
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('onboarding_complete')

    # ### end Alembic commands ###
