"""add_srs_snapshot_to_session_word

Revision ID: 7d9e8b83cb7e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 22:55:22.249116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9e8b83cb7e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('srs_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_word', schema=None) as batch_op:
        batch_op.drop_column('srs_snapshot')

    # ### end Alembic commands ###
