"""empty message

Revision ID: b28b769fd3c7
Revises: b8c9d0e1f2a3
Create Date: 2026-04-21 17:34:09.219145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28b769fd3c7'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_ds', sa.DateTime(), nullable=False),
    sa.Column('expires_ds', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_profile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_profile_user_id_fkey'), 'user', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))

    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
