"""add_ai_practice_fields_and_session_word_attempt

Revision ID: ee4a2028e5da
Revises: ae3b488cf0b1
Create Date: 2026-02-21 23:30:32.745856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4a2028e5da'
down_revision = 'ae3b488cf0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_word_attempt',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('usage_score', sa.Float(), nullable=True),
    sa.Column('naturalness_score', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_ds', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id', 'session_id'], ['session_word.word_id', 'session_word.session_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('session_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('grammar_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('usage_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('naturalness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('words_per_session', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_column('words_per_session')
        batch_op.drop_column('summary_text')

    with op.batch_alter_table('session_word', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('naturalness_score')
        batch_op.drop_column('usage_score')
        batch_op.drop_column('grammar_score')
        batch_op.drop_column('word_order')

    op.drop_table('session_word_attempt')
    # ### end Alembic commands ###
